### ISSUE TITLE
Число заблокированных объектов и время блокировки

### ISSUE THREAD

**Issue by kulpin74** [kulpin74/zabbix-1c#1]
Добавить мониторинг объектов заблокированных БД и время блокировки. Есть ли необходимость в этом?

**Comment by itopt** [comment]
да, конечно + объемы данных за 5 минут + всего

**Comment by kulpin74** [comment]
Добавил.
По объемам данных добавлено изменение между опросами. Объем данных всего мне кажется малоинформативен
