### ISSUE TITLE
Нет некоторых данных

### ISSUE THREAD

**Issue by HDaemon** [kulpin74/zabbix-1c#10]
Добрый день! Подскажите в Графиках Infobase data нет данных по Data и Blocked objects by DMS. Возможно я снова где-то что-то упустил?
![Снимок экрана от 2021-04-20 10-24-51](https://user-images.githubusercontent.com/3938745/115354798-b1952100-a1c2-11eb-90ef-114ac04bff93.png)

**Comment by HDaemon** [comment]
Разобрался. При импорте шаблона эти элементы создаются не активированными, так задумано?

**Comment by kulpin74** [comment]
Добрый,

Да, мне они не пригодились для какого-то анализа, собственно поэтому я их отключил, что бы не хранить данные по ним, но удалять не стал.  
В общем-то там же можно достать все данные которые ras возвращает, весь вопрос что потом делать с этими данными.

**Comment by kulpin74** [comment]
А ну и еще один ньюанс, данные возвращаемые ras они в разрезе сессий, а я их агрегирую, ну и мне кажется, что в агрегированном виде они не настолько показательны.  
В общем надо понимать, зачем собирать данные и какие выводы делать, у меня сложилось такое понимание только по кол-ву сессий.
