### ISSUE TITLE
импорт шаблона в Zabbix 5.0.20

### ISSUE THREAD

**Issue by serega1372** [kulpin74/zabbix-1c#11]
Добрый день
подскажите как импортировать ваш шаблон в Zabbix 5.0.20?

выдает ошибку:
Ошибочный тег "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": неожиданный тег "snmp_community".

**Comment by kulpin74** [comment]
Добрый день,

Весьма занятно, проверил, без проблем импортируется в 5.2.1 что под рукой был. Подобные ошибки встречались когда новый шаблон импортируется в старый Заббикс, но шаблон сохранен аж в 4.2 версии. Могу экспортировать шаблон из версии 5.2, но не уверен что ошибка пропадет.

**Comment by kulpin74** [comment]
Докинул шаблон для 5.2 - https://github.com/kulpin74/zabbix-1c/blob/master/1c-zabbix(5.2).xml
