### ISSUE TITLE
python script cannot run

### ISSUE THREAD

**Issue by mr-migre** [kulpin74/zabbix-1c#13]
I`ve installed on Windows server 2012 R2 with Python python-3.10.2-amd64
trying to run first script ib_list.py
RAS is fine, checked with RAC cluster info 

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

===================== RESTART: C:\zabbix\scripts\ib_list.py ====================
Traceback (most recent call last):
  File "C:\zabbix\scripts\ib_list.py", line 21, in <module>
    cluster_res = subprocess.check_output(['rac', 'cluster', 'list']).decode(C_PAGE).strip()
  File "C:\Program Files\python37\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\python37\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\python37\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\python37\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kulpin74** [comment]
Do you add to PATH system variable location of RAC? Something like c:\Program Files\1cv8\8.X.XX.XXXX\bin\

**Comment by mr-migre** [comment]
Ага, только не перегружал систему.

**Comment by kulpin74** [comment]
Без перезагрузки оно в силу не вступит

**Comment by mr-migre** [comment]
Вы правы, простите за тупость :) - Если вам не трудно, добавьте в описание пункт про перезагрузку :)
