### ISSUE TITLE
Скрипт

### ISSUE THREAD

**Issue by XmakcX** [kulpin74/zabbix-1c#14]
Здравствуйте!
Подскажите пожалуйста, куда необходимо скопировать скрипты и файл конфигурации?
"необходимо положить файлы *.py из каталога scripts и файл конфигурации 1c_zabbix.conf."
агент у меня установлен -C:\Program Files\Zabbix Agent\

**Comment by kulpin74** [comment]
`1c_zabbix.conf` положить в каталог `zabbix_agentd.d`.  
Так как путь установки другой, необходимо изменить пути в файле `1c_zabbix.conf`  
Сейчас они с учетом того что:
    zabbix agent - c:\zabbix
    python - c:\Program Files\Python37\python.exe

**Comment by XmakcX** [comment]
спасибо за ответ, при перезапуске агент выдает ошибку
![image](https://user-images.githubusercontent.com/90900939/157821605-98114df3-0efd-4059-a4ad-f7a8df256177.png)

**Comment by kulpin74** [comment]
Приведите текущее содержание `1c_zabbix.conf`, но подозреваю что в кавычки не взяли путь с пробелами

**Comment by XmakcX** [comment]
# Если не используется администратор кластера
#UserParameter=1cEnt.infobases, "c:\Program Files\Python310\python.exe" c:\zabbix\scripts\ib_list.py
#UserParameter=1cEnt.sessions[*], "c:\Program Files\Python37\python.exe" c:\zabbix\scripts\sess_list.py $1 $2

# Если администратор кластера существует
UserParameter=1cEnt.sessions[*], "c:\Program Files\Python310\python.exe" C:\Program Files\Zabbix Agent\scripts\ib_list.py
UserParameter=1cEnt.sessions[*], "c:\Program Files\Python310\python.exe" C:\Program Files\Zabbix Agent\scripts\sess_list.py $1 $2

**Comment by kulpin74** [comment]
> UserParameter=1cEnt.sessions[_], "c:\Program Files\Python310\python.exe" C:\Program Files\Zabbix Agent\scripts\ib_list.py UserParameter=1cEnt.sessions[_], "c:\Program Files\Python310\python.exe" C:\Program Files\Zabbix Agent\scripts\sess_list.py $1 $2

C:\Program Files\Zabbix Agent\scripts\sess_list.py должно быть заключено в кавычки

**Comment by XmakcX** [comment]
UserParameter=1cEnt.sessions[*], "c:\Program Files\Python310\python.exe" "C:\Program Files\Zabbix Agent\scripts\ib_list.py"
UserParameter=1cEnt.sessions[*], "c:\Program Files\Python310\python.exe" "C:\Program Files\Zabbix Agent\scripts\sess_list.py" $1 $2
![image](https://user-images.githubusercontent.com/90900939/157824434-400c5497-6b44-41fb-bb54-a451634ab1c9.png)
всё равно ошибка..

**Comment by kulpin74** [comment]
Судя по ошибке похоже что какие-то спец символы перед `UserParameter` есть. 

Ну и похоже никто никогда не пробовал использовать:
```
# Если администратор кластера существует
#UserParameter=1cEnt.sessions[*], "c:\Program Files\Python37\python.exe" c:\zabbix\scripts\sess_list.py $1 $2 cluster_username cluster_password
#UserParameter=1cEnt.sessions[*], "c:\Program Files\Python37\python.exe" c:\zabbix\scripts\sess_list.py $1 $2 cluster_username cluster_password
```
Тут черт знает что, счаз залью правки. Но судя по всему вы это не используете, внесите правки в первый раздел

**Comment by XmakcX** [comment]
![image](https://user-images.githubusercontent.com/90900939/157840426-4feb193f-0968-4693-a8e1-ce4b6dc69ded.png)

#Если не используется администратор кластера
UserParameter=1cEnt.infobases, "c:\Program Files\Python37\python.exe" c:\zabbix\scripts\ib_list.py
UserParameter=1cEnt.sessions[*], "c:\Program Files\Python37\python.exe" c:\zabbix\scripts\sess_list.py

**Comment by XmakcX** [comment]
> ![image](https://user-images.githubusercontent.com/90900939/157840426-4feb193f-0968-4693-a8e1-ce4b6dc69ded.png)
> 
> #Если не используется администратор кластера UserParameter=1cEnt.infobases, "c:\Program Files\Python37\python.exe" c:\zabbix\scripts\ib_list.py UserParameter=1cEnt.sessions[*], "c:\Program Files\Python37\python.exe" c:\zabbix\scripts\sess_list.py
закрыл в кавычки скрипты
![image](https://user-images.githubusercontent.com/90900939/157840935-8fbf5934-48f8-49e7-8093-67449848df44.png)

**Comment by kulpin74** [comment]
Вставьте содержимое вашего файла 1c_zabbix.conf как код, при обычной вставке все разъезжается, не понятно что же в файле... Ну либо в телеграм пришлите файл @kulpin_a

**Comment by XmakcX** [comment]
`#Если не используется администратор кластера
UserParameter=1cEnt.infobases, "c:\Program Files\Python310\python.exe" C:\Program Files\Zabbix Agent\scripts\ib_list.py 
UserParameter=1cEnt.sessions[*], "c:\Program Files\Python310\python.exe" C:\Program Files\Zabbix Agent\scripts\sess_list.py $1 $2

#Если администратор кластера существует
#UserParameter=1cEnt.sessions[*], "c:\Program Files\Python37\python.exe" c:\zabbix\scripts\sess_list.py $1 $2 cluster_username cluster_password
#UserParameter=1cEnt.sessions[*], "c:\Program Files\Python37\python.exe" c:\zabbix\scripts\sess_list.py $1 $2 cluster_username cluster_password
#UserParameter=1cEnt.sessions[*], "c:\Program Files\Python310\python.exe" "C:\Program Files\Zabbix Agent\scripts\ib_list.py"
#UserParameter=1cEnt.sessions[*], "c:\Program Files\Python310\python.exe" "C:\Program Files\Zabbix Agent\scripts\sess_list.py" $1 $2`

**Comment by XmakcX** [comment]
> Вставьте содержимое вашего файла 1c_zabbix.conf как код, при обычной вставке все разъезжается, не понятно что же в файле... Ну либо в телеграм пришлите файл @kulpin_a

спасибо за помощь, данные подтянулись, графики вытянул из прототипов, в скриптах прописал путь напрямую.
