### ISSUE TITLE
Ошибка Invalid discovery rule value: cannot parse as a valid JSON object:

### ISSUE THREAD

**Issue by AlexDezhnev** [kulpin74/zabbix-1c#16]
Сервер Zabbix 5.0.25 LTS
Клиент 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
1C 8.3.20.1914/Postgres 14

Два идентичных сервера1С, настроены одинаково, версии софта одинаковые

На одном мониторинг заработал корректно, на втором Zabbix сервер выдает ошибку у Discovery rule

[Template 1C Enterprise]: [Infobases]
"Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
File "/etc/zabbix/scripts/ib_list.py", line 21, in <module>
cluster_res = subprocess.check_output(['rac', 'clu"

Удаление и создание хоста заново не помогают

**Comment by kulpin74** [comment]
Могу предположить что нет пути до rac  в PATH. Либо не было перезагрузки после внесения правок.
Можно прописать полный путь до `rac` в py файлах.

**Comment by AlexDezhnev** [comment]
Почему-то не прописалась символьная ссылка до rac. Все взлетело. Большое спасибо!

**Comment by kulpin74** [comment]
Да не за что )
