### ISSUE TITLE
Debian + 8.3.22.1750 - не работает опрос

### ISSUE THREAD

**Issue by AlexDezhnev** [kulpin74/zabbix-1c#18]
На сервер 1С баз пока нет

В логах zabbix-сервера ошибка:
"discovery rule "1c-server:1cEnt.infobases" became not supported: Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
  File "/etc/zabbix/scripts/ib_list.py", line 36, in <module>
    ib_list.append({**get_dict_from_string(ib),
  File"

На сервере 1С
#python3 /etc/zabbix/scripts/ib_list.py
Traceback (most recent call last):
  File "/etc/zabbix/scripts/ib_list.py", line 36, in <module>
    ib_list.append({**get_dict_from_string(ib),
  File "/etc/zabbix/scripts/ib_list.py", line 16, in get_dict_from_string
    key, value = i.split(':', 1)
ValueError: not enough values to unpack (expected 2, got 1)

Система (виртуальная машина)
Linux 1c-server 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64

1С сервер 
 srv1cv8-8.3.22.1750@default.service - 1C:Enterprise Server 8.3 (8.3.22.1750) (default)
     Loaded: loaded (/opt/1cv8/x86_64/8.3.22.1750/srv1cv8-8.3.22.1750@.service; enabled; vendor preset: ena>
     Active: active (running) since Wed 2023-03-01 13:53:27 MSK; 7min ago

RAS
ras.service - RAS
     Loaded: loaded (/etc/systemd/system/ras.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-03-01 13:53:30 MSK; 8min ago

Zabbix-agent
zabbix-agent.service - Zabbix Agent
     Loaded: loaded (/lib/systemd/system/zabbix-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-03-01 13:53:30 MSK; 8min ago

При установке хотя бы одной базы все работает.

Хорошо бы сделать внятную реакцию на отсутствие баз на сервере

**Comment by kulpin74** [comment]
> Хорошо бы сделать внятную реакцию на отсутствие баз на сервере

Какие предложения, можно убрать ошибку просто и соответственно обнаружение не будет давать ошибку. Возможно есть другие предложения?

**Comment by AlexDezhnev** [comment]
Думаю этого вполне достаточно. Я сам не сразу догадался, что дело в отсутствии баз. Если бы скрипт просто не выдавал ошибку, я бы даже не заподозрил неладное - настроил бы мониторинг, добавил базы, и все было бы отлично

**Comment by kulpin74** [comment]
Есть ли возможность проверить правки в скриптах? Мне сейчас затруднительно смоделировать ситуацию кластера 1с без баз ((( 

Pull request прикрепил к задаче....

**Comment by AlexDezhnev** [comment]
На этой неделе, думаю, получится

пн, 27 мар. 2023 г. в 10:59, Alexey Kulpin ***@***.***>:
