### ISSUE TITLE
Value should be a JSON object

### ISSUE THREAD

**Issue by Katausy** [kulpin74/zabbix-1c#2]
День добрый!
Проверка работоспособность py-запроса (запуск из папки c:\zabbix\scripts\)
Время выполнения скриптов - менее 3 секунд для списка баз, менее 2 сек для подключений

[sess.txt](https://github.com/kulpin74/zabbix-1c/files/2610142/sess.txt)
[list.txt](https://github.com/kulpin74/zabbix-1c/files/2610143/list.txt)

На всякий случай - 
Агент 3,2,0,10000
лог в режиме дебага
[zabbix_agentd.log](https://github.com/kulpin74/zabbix-1c/files/2610163/zabbix_agentd.log)
конфиг ZABBIX-агента
[zabbix_agentd.zip](https://github.com/kulpin74/zabbix-1c/files/2610153/zabbix_agentd.zip)

**Comment by kulpin74** [comment]
Не до конца уверен, попробуйте подменить файлик скрипта вот этим 
[ib_list.zip](https://github.com/kulpin74/zabbix-1c/files/2612351/ib_list.zip)
Если все равно останется ошибка - на сервере Zabbix выполните команду `zabbix_get -s ip_addr -k 1cEnt.infobases`, где ip_addr - адрес сервера 1с, ну и где собственно Заббикс агент со всеми скриптами стоит. Интересно что получится.

**Comment by Katausy** [comment]
root@zabbix:/home/zabbix# zabbix_get -s 192.168.124.42 -k 1cEnt.infobases

Command 'zabbix_get' not found, but can be installed with:

apt install zabbix-proxy-mysql
apt install zabbix-proxy-pgsql
apt install zabbix-proxy-sqlite3
apt install zabbix-server-mysql
apt install zabbix-server-pgsql

-------------------
итого - у меня недоустановлен Zabbix ?

погуглил - да, в последних версиях zabbix идет без данного модуля, нужно руками добавлять.
 apt install zabbix-get "в помощь"

**Comment by kulpin74** [comment]
Странно это все...
А как ставили заббикс? Из репозитория заббикса? Или каким-то другим методом?
Вот подобный вопрос https://www.zabbix.com/forum/in-russian/38503-%D0%93%D0%B4%D0%B5-%D0%B8%D1%81%D0%BA%D0%B0%D1%82%D1%8C-zabbix_get-%D0%B8-zabbix_send
попробуйте apt install zabbix-get.  
У нас он уже установлен, ставили с репозитория заббикса
root@zabbix:~# apt install zabbix-get  
Reading package lists... Done  
Building dependency tree  
Reading state information... Done  
zabbix-get is already the newest version (1:4.0.1-1+xenial).  
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

UPD 
Не помню что бы доустанавливали этот пакет, хотя 4 не с нуля ставили а обновляли

**Comment by Katausy** [comment]
Пришлось отключить шифрование, но зато получил "результат":

 zabbix_get -s 192.168.124.42 -k 1cEnt.infobases
▒▒▒⥬▒ ▒▒ 㤠▒▒▒▒ ▒▒▒▒ 㪠▒▒▒▒▒ ▒▒▒▒.

Кодировка?

**Comment by kulpin74** [comment]
Хмммм, ну результат по размеру не похож на тот что д.б. :( Явно ошибка какая-то, под кем выполняется служба заббикс агента?

**Comment by kulpin74** [comment]
Попробуйте с 1с машины выполнить ту же команду, там есть zabbix_get по умолчанию, только в конф файл нужно прописать адрес этой машины в Server.

**Comment by Katausy** [comment]
минутку

**Comment by Katausy** [comment]
c:\zabbix>zabbix_get -s 127.0.0.1 -k 1cEnt.infobases
Системе не удается найти указанный путь.

но из CMD скрипты отрабатывали нормально

**Comment by Katausy** [comment]
![image](https://user-images.githubusercontent.com/45284431/49003234-5b535d80-f183-11e8-90c2-fdfb20c8f799.png)

**Comment by Katausy** [comment]
![image](https://user-images.githubusercontent.com/45284431/49003342-8ccc2900-f183-11e8-913b-59d3aca736de.png)

**Comment by kulpin74** [comment]
Python в другом каталоге стоит, у меня 64 разрядный "c:\Program Files\Python37\python.exe"
А у вас "c:\Program Files (x86)\Python37\python.exe"
Нужно поменять путь в конф файле заббикса
Либо попробовать путь убрать совсем, по PATH его должен найти

**Comment by Katausy** [comment]
Вы абсолютно правы.
сам к этому же пришел, сравнивая пути.

Спасибо Вам огромное!

**Comment by kulpin74** [comment]
Не за что.
Маякните если все получится, я изменения внесу в readme

**Comment by Katausy** [comment]
затупил, т.к. Вы ранее разбирали вариант, когда как раз path не был поправлен и не отрабатывало из CMD

тестирую.

**Comment by Katausy** [comment]
все заработало.

**Comment by kulpin74** [comment]
Ну отлично, я вчера ещё добавки выложил, в частности для вас тоже, кол-во веб клиентов не мониторилось )
