### ISSUE TITLE
Вычисляемое значение

### ISSUE THREAD

**Issue by Katausy** [kulpin74/zabbix-1c#3]
День добрый!
Не подскажите, как записать "формулу" вычисляемого значения числа работающих в кластере пользователей, как сумму последних значений клиентов (тонкий +  толстый + web) ?
У нас Web до 80 сессий в рабочий день.
Попробовал по описанию - вместо значений получаю ошибку, в которой видно, что берется не числовое значение ключа, а его ID.

Периодически всплавает проблема с нехваткой ключей, хотелось бы иметь возможность повесить триггер на пороговое и критическое значение.

По графикам не совсем удобно смотреть получается, да и триггеры вешать надо на сумму пользователей, без разбивки на типы.
![image](https://user-images.githubusercontent.com/45284431/49102319-503f2100-f29a-11e8-8f5a-ec5c69d2d2e2.png)

p.s. не посоветуете монитор ключей 1С, который Вы считаете работоспособным? используем 2х100 программных + 1х100 аппаратный, хочется тоже повесить триггер на их утилизацию.

**Comment by kulpin74** [comment]
Доброго утра!
По вычисляемому вот так нужно записать:
![default](https://user-images.githubusercontent.com/31801328/49133428-21a06500-f2f1-11e8-8c0a-dcf26c67efe2.png)
last("1cEnt.sessions.designers[{#INFOBASE}]") + last("1cEnt.sessions.bjobs[{#INFOBASE}]") + last("1cEnt.sessions.comconn[{#INFOBASE}]") + last("1cEnt.sessions.thickClient[{#INFOBASE}]") + last("1cEnt.sessions.thinClient[{#INFOBASE}]") + last("1cEnt.sessions.webclients[{#INFOBASE}]")

Ну и триггер на него повесить.

По поводу ключей планирую это тоже допилить, проблема-то такая же в общем... Просто кол-во сессий мониторить не совсем корректный вариант, если клиент получил лицензию с менеджера лицензий, то она же применится на все сессии. В общем есть мысли как сделать, в процессе, как время будет - допилю.

**Comment by Katausy** [comment]
Доброго времени суток!
Вроде бы то же самое записывал, но не "взлетело". 
Спасибо большое!

По поводу подсчета лицензий - у нас большая часть программных, они раздаются 1шт/сессия
Аппаратный (что нелогично) оказался на WEB.
так что в нашем случае временно можно будет триггер сделать по сумме сессий.

Находил пару вариантов - но они годны только для ручного вывода в виде "стекируемого графика", т.к. имена ключей меняются раз в несколько часов.

**Comment by Katausy** [comment]
Попробовал Ваш вариант и получил знакомую ошибку.
Не зря подумал, что примерно так и пробовал :)

"Cannot evaluate function "last()": item "app-2.pivzavoz.local:1cEnt.sessions.webclients[all_infobases]" does not exist."
Cannot evaluate function "last()": item "app-2.pivzavoz.local:1cEnt.sessions.webclients[c2338700-83ef-47cd-a6ad-5ebebf1bbdc2]" does not exist.
и так далее
![image](https://user-images.githubusercontent.com/45284431/49167781-f309a500-f357-11e8-811f-fe0f9f575f63.png)

Проблема в том, что если значения нет, то оно не равно 0 и не может складыватся? 
Получается, что нужно либо делать "СУММА, Если значение <> NULL", либо под каждую базу делать руками только те значения, которые гарантировано имеются, иначе словим опять ошибку...
не вариант: web, например, используется внешними партнерами, которые ночью спят и число сессий схлопывается в "0".

**Comment by kulpin74** [comment]
Странно, я проверил прежде чем ответить, все посчитал у меня, попозже еще гляну. И там в любом случае с агента ноль возвращается, даже если нет этого типа клиента

**Comment by kulpin74** [comment]
Можете прислать принтскрин настройки элемента?
У меня вот так все:
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/31801328/49171581-e2553100-f34f-11e8-8b2b-3365446bca10.png">
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/31801328/49171676-19c3dd80-f350-11e8-911a-92babb8eeec1.png">
Единственное отличие от утреннего моего принтскрина - изменил интервал обновления, поставил 10 мин - не имеет смысла ставить интервал меньше, чем запрос данных с агента, но и с 1 минутой работало без проблем

**Comment by kulpin74** [comment]
И кстати странно ругается только на webclients, который последний в списке 
СТОП, а когда вы обновили скрипт sess_list.py? И обновили ли шаблон? Я два дня назад выложил обновление и для вас как раз добавил вебклиентов, до этого их не было, и в скрипт и в шаблон
Может потому и ругается что webclient ов нет, вот и не может сложить?

**Comment by Katausy** [comment]
sess_list.py обновлял, но шаблон - руками "по образу и подобию" правил сам.
Сейчас попробую.

**Comment by Katausy** [comment]
День добрый!
обновил все до последней версии - все ЗАМЕЧАТЕЛЬНО! 
еще раз СПАСИБО!

**Comment by kulpin74** [comment]
Доброго утра!
Ну отлично.
Еще уточняющий вопрос по ключам: правильно ли я понимаю что текущий подсчет сессий для всех баз вас полностью устраивает? Или вы хотите смотреть отдельно по ключам сколько сессий в на какой ключ повесилось?

**Comment by Katausy** [comment]
День бодрый!
Для всех баз - необходимый и достаточный вариант.
по базам раздельно нет смысла - все базы в кластере, ключи "шарятся"

**Comment by kulpin74** [comment]
Не, я имел в виду по ключам, сколько с какого взялось, по базам конечно бессмысленно. Можно попросить прислать вывод [json_sess_list.zip](https://github.com/kulpin74/zabbix-1c/files/2636613/json_sess_list.zip), желательно когда много пользователей разных в базах?
Это вывод rac session list в json завернутый, хочу попробовать выделить ключи. У меня только аппаратный ключ, у вас более разнообразно :) Если это вообще возможно - то на почту kulpin@mail.ru лучше наверное, что бы тут не светить, там все же базы, пользователи...
