### ISSUE TITLE
ib_list.py возвращает ошибку при наличии 2 кластеров на сервере

### ISSUE THREAD

**Issue by Katausy** [kulpin74/zabbix-1c#4]
Доброго времени суток!

Если будет минутка, прошу Вашей помощи

Для тестирования необходимо было создать второй кластер на сервере. Программеры прикрутили.
В итоге статистика перестала работать. 

Тестирование при ручном запуске ib_list.py показало:
```
C:\zabbix\scripts>ib_list.py
Traceback (most recent call last):
  File "C:\zabbix\scripts\ib_list.py", line 13, in <module>
    cluster = getDictFromString(cluster_res)
  File "C:\zabbix\scripts\ib_list.py", line 8, in getDictFromString
    dict_el = {**dict_el, **dict([[j.strip() for j in i.split(' :')]])}
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

Запустил руками RAC:
```
C:\zabbix\scripts>rac cluster list
cluster                       : d0e04812-1022-4664-8575-3552e1aecd37
host                          : APP-1C02
port                          : 1541
name                          : "Локальный кластер"
expiration-timeout            : 60
lifetime-limit                : 8600
max-memory-size               : 20971520
max-memory-time-limit         : 30
security-level                : 0
session-fault-tolerance-level : 0
load-balancing-mode           : performance
errors-count-threshold        : 0
kill-problem-processes        : 0

cluster                       : e0307b33-a0e0-4921-80e5-5fe199bfc9e7
host                          : app-1c02
port                          : 1741
name                          : "Кластер Гилева"
expiration-timeout            : 30
lifetime-limit                : 8600
max-memory-size               : 4194304
max-memory-time-limit         : 0
security-level                : 0
session-fault-tolerance-level : 0
load-balancing-mode           : memory
errors-count-threshold        : 0
kill-problem-processes        : 0
```
т.е. получаю 2 ID кластера, что и вызывает ошибку

Запрос RAC по ID вручную отрабатывает нормально, получаю то, что нужно:
```
C:\zabbix\scripts>rac infobase --cluster=d0e04812-1022-4664-8575-3552e1aecd37 summary list
infobase : 535d5611-5737-42c1-8c9b-487099a06f13
name     : pivzavoz_new
descr    : "pivzavoz_new"
```

Вопрос/просьба - можно ли ограничить работу функции  getDictFromString(txtBlock) первым найденным значением?
Или же - как его указать "в лоб" в скрипте, в случае подобного "нешаблонного" применения? 

Насколько понимаю, необходимо указать значение cluster вручную, т.е. убрать вызов функции в строке
`cluster = getDictFromString(cluster_res)`

(мои извинения, в Python вообще не ориентируюсь, просто комментирование строки и попытка указать ID вручную - вызывает новые ошибки)

Совсем в идеале - иметь возможность в конфиге указать,  какой по счету ID использовать, но, думаю, таких экспериментаторов, как мы, немного и время на доработку несопоставимо с итоговым результатом.

Заранее благодарен

**Comment by kulpin74** [comment]
Добрый день!
Отличный вариант, не было под рукой двух кластеров.
С Вашей помощью добьем и несколько кластеров. Как лучше реализовать, в названии item добавить имя кластера, либо в разные группы собрать? Либо какой-то другой вариант есть в мыслях?

**Comment by kulpin74** [comment]
В принципе все готово, но надо еще шаблон менять и история накроется :( Могу обновление выложить, но с вас сначала проверка что работает с двумя кластерами - выложил файлик [ib_list1.py,](https://github.com/kulpin74/zabbix-1c/blob/master/scripts/ib_list1.py) либо его вывод выложите, либо проверьте что отрабатывает без ошибок и в поле CLUSTER, CLUSTER_NAME все корректно.

**Comment by Katausy** [comment]
День добрый!
Думаю, оптимально будет добавить имя кластера в item.

Потерю истории я потреплю :)
сейчас проверим работу файлика

**Comment by Katausy** [comment]
Работает:
```
C:\zabbix\scripts>ib_list1.py
{"data": [{"{#INFOBASE}": "56c7f619-f2bc-40ac-a855-63be7b22f188", "{#NAME}": "gilev_vblock", "{#DESCR}": "", "{#CLUSTER}": "e0307b33-a0e0-4921-80e5-5fe199bfc9e7", "{#CLUSTER_NAME}": "\u041a\u043b\u0430\u0441\u0442\u0435\u0440 \u0413\u0438\u043b\u0435\u0432\u0430"}, {"{#INFOBASE}": "7e1c2c76-fc6b-4db1-b937-64174c83cc9b", "{#NAME}": "gilev_kna", "{#DESCR}": "", "{#CLUSTER}": "e0307b33-a0e0-4921-80e5-5fe199bfc9e7", "{#CLUSTER_NAME}": "\u041a\u043b\u0430\u0441\u0442\u0435\u0440 \u0413\u0438\u043b\u0435\u0432\u0430"}, {"{#INFOBASE}": "all_infobases", "{#NAME}": "All_IBs_of_cluster", "{#DESCR}": "all_infobases", "{#CLUSTER}": "e0307b33-a0e0-4921-80e5-5fe199bfc9e7", "{#CLUSTER_NAME}": "\u041a\u043b\u0430\u0441\u0442\u0435\u0440 \u0413\u0438\u043b\u0435\u0432\u0430"}, {"{#INFOBASE}": "535d5611-5737-42c1-8c9b-487099a06f13", "{#NAME}": "pivzavoz_new", "{#DESCR}": "pivzavoz_new", "{#CLUSTER}": "d0e04812-1022-4664-8575-3552e1aecd37", "{#CLUSTER_NAME}": "\u041b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043a\u043b\u0430\u0441\u0442\u0435\u0440"}, {"{#INFOBASE}": "all_infobases", "{#NAME}": "All_IBs_of_cluster", "{#DESCR}": "all_infobases", "{#CLUSTER}": "d0e04812-1022-4664-8575-3552e1aecd37", "{#CLUSTER_NAME}": "\u041b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043a\u043b\u0430\u0441\u0442\u0435\u0440"}]}

```
Русское название кластеров идет в urlencode

**Comment by kulpin74** [comment]
Выложил обновления - проверяйте, у меня с 1 кластером все мониторится нормально.

**Comment by Katausy** [comment]
На версии 4.0 импорт шаблона идет с ошибками:

> Ошибочный тег "/zabbix_export/version": неподдерживаемый номер версии.
Это поправил на 4.0 с 4.2

> Ошибочный тег "/zabbix_export/templates/template(1)": неожиданный тег "tags".
Это уже непонятно, т.к. в листинге **tags** встречается только 1 раз, в строке 998, причем в виде закрывающего тэга

похоже, дело опять пахнет обновлением версии :)

**Comment by kulpin74** [comment]
Ну да я на 4.2 ушел из-за тротлинга и js. Я думаю эту строку можно просто удалить. Она в самом конце.

**Comment by Katausy** [comment]
простое удаление не помогло.
Делаю полный бэкап сервера с zabbix, буду обновляться.

**Comment by Katausy** [comment]
Обновился.
Список баз в кластере - получаю:
![image](https://user-images.githubusercontent.com/45284431/59635587-09981200-916b-11e9-9664-931025476ac2.png)

Но "последнее значение" выглядит вот так:

> 18.06.2019 01:45:55 | Traceback (most recent call last):   File "c:\zabbix\scripts\sess_list.py", line 22, in <module>     cmd_list = ['rac', 'session', 'list', '--cluster=' + sys.argv[2]] IndexError: list index out of range
> -- | --

**Comment by Katausy** [comment]
C:\zabbix\scripts>ib_list.py
{"data": [{"{#INFOBASE}": "56c7f619-f2bc-40ac-a855-63be7b22f188", "{#NAME}": "gilev_vblock", "{#DESCR}": "", "{#CLUSTER}": "e0307b33-a0e0-4921-80e5-5fe199bfc9e7", "{#CLUSTER_NAME}": "\u041a\u043b\u0430\u0441\u0442\u0435\u0440 \u0413\u0438\u043b\u0435\u0432\u0430"}, {"{#INFOBASE}": "7e1c2c76-fc6b-4db1-b937-64174c83cc9b", "{#NAME}": "gilev_kna", "{#DESCR}": "", "{#CLUSTER}": "e0307b33-a0e0-4921-80e5-5fe199bfc9e7", "{#CLUSTER_NAME}": "\u041a\u043b\u0430\u0441\u0442\u0435\u0440 \u0413\u0438\u043b\u0435\u0432\u0430"}, {"{#INFOBASE}": "all_infobases", "{#NAME}": "All_IBs_of_cluster", "{#DESCR}": "all_infobases", "{#CLUSTER}": "e0307b33-a0e0-4921-80e5-5fe199bfc9e7", "{#CLUSTER_NAME}": "\u041a\u043b\u0430\u0441\u0442\u0435\u0440 \u0413\u0438\u043b\u0435\u0432\u0430"}, {"{#INFOBASE}": "535d5611-5737-42c1-8c9b-487099a06f13", "{#NAME}": "pivzavoz_new", "{#DESCR}": "pivzavoz_new", "{#CLUSTER}": "d0e04812-1022-4664-8575-3552e1aecd37", "{#CLUSTER_NAME}": "\u041b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043a\u043b\u0430\u0441\u0442\u0435\u0440"}, {"{#INFOBASE}": "b4b6c5f5-d39e-4f62-bfbc-c5395d1e2328", "{#NAME}": "Gilev180819", "{#DESCR}": "", "{#CLUSTER}": "d0e04812-1022-4664-8575-3552e1aecd37", "{#CLUSTER_NAME}": "\u041b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043a\u043b\u0430\u0441\u0442\u0435\u0440"}, {"{#INFOBASE}": "all_infobases", "{#NAME}": "All_IBs_of_cluster", "{#DESCR}": "all_infobases", "{#CLUSTER}": "d0e04812-1022-4664-8575-3552e1aecd37", "{#CLUSTER_NAME}": "\u041b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043a\u043b\u0430\u0441\u0442\u0435\u0440"}]}

**Comment by Katausy** [comment]
Запуск "вручную" возвращает нормальные значения

C:\zabbix\scripts>sess_list.py pivzavoz_new d0e04812-1022-4664-8575-3552e1aecd37
{"COMConnection": 0, "Designer": 0, "1CV8C": 0, "1CV8": 17, "BackgroundJob": 4, "WebClient": 0, "blockedByDBMS": 0, "dbProcTook": 5033, "bytesAll": 301385646}

**Comment by kulpin74** [comment]
Хммм, ну самый правдоподобный вариант: 1s_zabbix.conf обновляли? Службу Заббикс агента перезапускали?
Если все да - тогда принт скринт настроек любого обнаруженного itema пришлите глянуть

**Comment by Katausy** [comment]
День бодрый!
Делал ночью, сейчас перепроверю.
Итак:

1s_zabbix.conf
`UserParameter=1cEnt.infobases, "C:\Program Files (x86)\Python37\python.exe" c:\zabbix\scripts\ib_list.py
UserParameter=1cEnt.sessions[*], "C:\Program Files (x86)\Python37\python.exe" c:\zabbix\scripts\sess_list.py $1 $2`

ib_list.py и sess_list.py Ваши, версия от 17/06/2019 0:01

Агент перезапущен.

могу дать Teamviewer v13

**Comment by Katausy** [comment]
Шаблон "отсоединил и очистил".
Обновил узел, присоединил шаблон обратно.

![image](https://user-images.githubusercontent.com/45284431/59656043-cfa02d80-91b5-11e9-8748-032d0c8ec56c.png)

здесь Ваш шаблон, все выглядит корректным.
Жду появления item`ов

**Comment by Katausy** [comment]
А вот и итемы:
![image](https://user-images.githubusercontent.com/45284431/59656168-2d347a00-91b6-11e9-83ed-fc5a3769d390.png)

Текст ошибки:

> Preprocessing failed for: Traceback (most recent call last):.. File "c:\zabbix\scripts\sess_list.py", line 22, in <module>...
1. Failed: cannot extract value from json by path "$.WebClient": cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
File "c:\zabbix\scripts\sess_list.py", line 22, in <module>
cmd_list = ['rac', 'session', 'list', '--cluster

**Comment by Katausy** [comment]
Появились итемы:
![image](https://user-images.githubusercontent.com/45284431/59656774-142cc880-91b8-11e9-9770-1e473f0663f7.png)

Текст ошибки:

> 
Preprocessing failed for: Traceback (most recent call last):.. File "c:\zabbix\scripts\sess_list.py", line 22, in <module>...
1. Failed: cannot extract value from json by path "$.WebClient": cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
File "c:\zabbix\scripts\sess_list.py", line 22, in <module>
cmd_list = ['rac', 'session', 'list', '--cluster

**Comment by kulpin74** [comment]
Странно это все, ну ок давайте в тимвью глянем, это быстрее будет. В мессенджер какой-нить предлагаю уйти, телеграм, скайп?

**Comment by Katausy** [comment]
согласен
telegram привязан к номеру +7(922)-207-65-45

**Comment by Katausy** [comment]
проблема решена.
Спасибо ОГРОМНОЕ!
