### ISSUE TITLE
Скрипт ib_list.py не выполняется

### ISSUE THREAD

**Issue by sailz1** [kulpin74/zabbix-1c#5]
Добрый день!
Спасибо за вашу работу.
у нас немного иная ситуация: кластеров два, но они разнесены на разные службы, слушаются на разных портах: 1540 и 2540
Установил 2 службы RAS, которые смотрят на разные порты и обращение RAC к RAS тоже на портах 1545 и 2545. 
Каким образом можно доработать скрипт, чтобы он работал?

**Comment by sailz1** [comment]
точнее, я уже исправил скрипты, чтобы он мог запускаться, явно прописал host:port
cluster_res = subprocess.check_output(['rac', 'cluster', 'list', '192.168.1.254:2545']).decode('cp866').strip()
Скрипт работает, итемы создаются и мониторятся

Как вариант можно создать еще 2 скрипта с нужными <host>[:<port>], и создавать второй комплект прототипов, но хотелось бы универсальности

**Comment by kulpin74** [comment]
Добрый день!

Не очень понял, RAC по идее должен увидеть оба кластера...
Что у вас пишет команда `rac cluster list`?
По крайней мере в случае с #4 было именно так

**Comment by sailz1** [comment]
Пишу с телефона, под рукой доступа к кластеру нет. Запрос "rac cluster list" возвращает единственный локальный кластер. Но, т.к в запросе не указан server:port то по умолчанию опрашивается localhost:1540, а в моем случае портов 2: 1540 и 2540.
И если я выполню запрос rac cluster list localhost:2540 вернет второй единственный локальный кластер.
На втором кластере живет база "документооборота" и такое решение не от меня и обусловлено тем, что проще перезапустить одну службу и выкинуть пользователей из "документооборота"

**Comment by sailz1** [comment]
И соответственно запрос rac infobase summary list --cluster=$cluster вернет кучу баз, а запрос rac infobase summary list --cluster=$cluster server:port вернет единственную базу "документооборот"

**Comment by kulpin74** [comment]
ок, в понедельник подумаю как элегантно решить задачку

**Comment by sailz1** [comment]
Я опробовал вариант создать массив строк cluster_res двумя запросами: 
cluster_res = subprocess.check_output(['rac', 'cluster', 'list', 'server:port']).decode('cp866').strip()
cluster_res += subprocess.check_output(['rac', 'cluster', 'list', 'server:port2']).decode('cp866').strip()
ib_li, но выходит ошибка.
А в идеале параметр server:port передавать скрипту, чтобы не компилировать .exe шник

**Comment by sailz1** [comment]
А вообще, не задумывались над вариантом, чтобы весь результат команды rac session list --cluser = $cluster    --infobaser $infobase собирать в Json и отдавать zabbix у, а там уже разбирать через зависимые элементы. Так любой желающий мог бы получить нужные ему результаты, например, мне интересно получать все количественные данные о соединениях

**Comment by kulpin74** [comment]
Доброго дня!

> Я опробовал вариант создать массив строк cluster_res двумя запросами:
> cluster_res = subprocess.check_output(['rac', 'cluster', 'list', 'server:port']).decode('cp866').strip()
> cluster_res += subprocess.check_output(['rac', 'cluster', 'list', 'server:port2']).decode('cp866').strip()
> ib_li, но выходит ошибка.
Просто сложить не получится

Самый простой вариант: можно передавать дополнительным параметром имя/адрес сервера. Но тогда придется копию шаблона делать на каждый дополнительный сервер.

Ну либо сделать более сложный шаблон, который будет оперировать массивом серверов RAS.

Простой вариант завтра видимо смогу выложить, сложный надо будет разбираться

**Comment by kulpin74** [comment]
> 
> 
> А вообще, не задумывались над вариантом, чтобы весь результат команды rac session list --cluser = $cluster --infobaser $infobase собирать в Json и отдавать zabbix у, а там уже разбирать через зависимые элементы. Так любой желающий мог бы получить нужные ему результаты, например, мне интересно получать все количественные данные о соединениях

Я не ставил себе задачей выгребать все, собирал только то что я могу как-то применить в анализе. Можно конечно выгрести все, но что с этим делать?

Как вариант можно попробовать передавать список параметров который необходим. В шаблоне по умолчанию оставить те что стандартные, если необходимо что-то экзотическое, то прям в шаблоне и указать что нужно еще. Как вам такой вариант?

**Comment by sailz1** [comment]
На самом деле я на вашу разработку вышел, когда искал примеры зависимых прототипов элементов для шаблона заббикса. 
Похожее решение сделал на powershell 5.1. Решение сырое, но рабочее. Через LLD создаются итемы. В качестве ключа указываются uuid базы, uuid кластера и адрес:порт сервера. Но мое решение для всех итемов запускал свой скрипт, а баз более 20шт, итемов более 200шт, в итоге агент не успевал передавать данные за отведенное время и сервер заббикса помечал его недоступным. 
Пришел к выводу, что нужно собирать все значения в целом по кластеру и в разрезе инфобаз через json.
Ваше решение тем и понравилось.
Более подробно написал на почту, если вы не против)

**Comment by kulpin74** [comment]
TODO: Добавить указание сервера RAS и порта в параметрах скриптов, по умолчанию localhost:1565, при передаче параметра использовать переданное
