### ISSUE TITLE
Cannot parse as a valid JSON object

### ISSUE THREAD

**Issue by HDaemon** [kulpin74/zabbix-1c#9]
Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
File "C:\Program Files\Zabbix Agent\scripts\ib_list.py", line 21, in <module>
cluster_res = subprocess.check

**Comment by HDaemon** [comment]
Запустил скрипт в консоли выполняется нормально, возвращает JSON.

**Comment by kulpin74** [comment]
Это сделали?
`В системную переменную PATH необходимо добавить путь где находится исполняемый файл rac.exe:
c:\Program Files\1cv8\8.X.XX.XXXX\bin\`

Именно в системную, не в пользовательскую

**Comment by HDaemon** [comment]
Прошу прощения за беспокойство, действительно моя невнимательность :)
